# Generated by Django 4.0.4 on 2023-11-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.empleado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.pack'),
        ),
        migrations.AddField(
            model_name='pack',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.actividad'),
        ),
        migrations.AddField(
            model_name='pack',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hotel'),
        ),
        migrations.AddField(
            model_name='pack',
            name='vuelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.vuelo'),
        ),
    ]
