# Generated by Django 4.0.4 on 2023-11-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='vu_imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='vuelo/'),
        ),
    ]
