# Generated by Django 4.0.4 on 2023-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': 'Packs'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='act_descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción de la actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='act_nombre',
            field=models.CharField(help_text='Andar a Caballo, Caminata guiada...', max_length=50, verbose_name='Nombre de la Actividad'),
        ),
    ]
