# Generated by Django 4.0.4 on 2023-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_actividad_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='act_imagen',
            field=models.ImageField(default='', upload_to='pack/'),
        ),
    ]
