# Generated by Django 4.0.4 on 2023-11-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reserva_actividad_reserva_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='actividad',
            field=models.ManyToManyField(blank=True, null=True, to='booking.actividad'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.ManyToManyField(blank=True, null=True, to='booking.hotel'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pack',
            field=models.ManyToManyField(blank=True, null=True, to='booking.pack'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo',
            field=models.ManyToManyField(blank=True, null=True, to='booking.vuelo'),
        ),
    ]
