# Generated by Django 4.0.4 on 2023-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_actividad_act_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ho_imagen',
            field=models.ImageField(default='', upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='pack',
            name='pa_imagen',
            field=models.ImageField(default='', upload_to='pack/'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='vu_imagen',
            field=models.ImageField(default='', upload_to='vuelo/'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='act_imagen',
            field=models.ImageField(default='', upload_to='actividad/'),
        ),
    ]
