# Generated by Django 4.0.4 on 2023-11-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_tipoactividad_actividad_act_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='act_imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='actividad/'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pa_imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pack/'),
        ),
    ]
