# Generated by Django 4.0.4 on 2023-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_pack_pa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='act_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
