# Generated by Django 4.0.4 on 2023-11-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_hotel_ho_imagen_pack_pa_imagen_vuelo_vu_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='vu_nombre',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='vu_destino',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='vu_origen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen'),
        ),
    ]
