# Generated by Django 4.0.4 on 2023-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_actividad_act_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pa_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
