# Generated by Django 4.0.4 on 2023-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_vuelo_vu_nombre_vuelo_vu_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='vu_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vuelo'),
        ),
    ]
