# Generated by Django 4.0.4 on 2023-11-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_vuelo_vu_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='vu_imagen',
        ),
    ]
