# Generated by Django 4.0.4 on 2023-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_vuelo_vu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ho_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
