# Generated by Django 4.0.4 on 2023-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_hotel_ho_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='ho_imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hotel/'),
        ),
    ]
