# Generated by Django 4.0.4 on 2023-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customizeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeemail',
            name='template',
            field=models.CharField(choices=[('template1', 'Plantilla 1'), ('template2', 'Plantilla 2'), ('template3', 'Plantilla 3')], default='template1', max_length=20),
        ),
        migrations.AlterField(
            model_name='customizeemail',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
