# Generated by Django 4.0.4 on 2023-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_countemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
