# Generated by Django 4.0.4 on 2023-11-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customizeemail_template_alter_customizeemail_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizeEmail',
        ),
    ]
