# Generated by Django 4.0.4 on 2023-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_registro',
        ),
    ]
