# Generated by Django 4.0.4 on 2023-11-14 10:47

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_customizeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
    ]
