# Generated by Django 4.0.4 on 2023-11-14 11:22

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_writemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writemail',
            old_name='Title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='writemail',
            name='content',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
