# Generated by Django 4.0.4 on 2023-11-14 11:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_title_writemail_name_alter_writemail_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writemail',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='writemail',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
