# Generated by Django 4.0.4 on 2023-11-14 16:17

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_writenewsletter_delete_writemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writenewsletter',
            name='content',
            field=django_quill.fields.QuillField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='writenewsletter',
            name='introduction',
            field=django_quill.fields.QuillField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='writenewsletter',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='writenewsletter',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='writenewsletter',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
