# Generated by Django 4.0.4 on 2023-11-14 16:20

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_writenewsletter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writenewsletter',
            name='content',
            field=django_quill.fields.QuillField(max_length=10000),
        ),
    ]
