# Generated by Django 4.0.4 on 2023-11-15 08:21

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_writenewsletter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writenewsletter',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
