# Generated by Django 4.0.4 on 2023-11-15 08:51

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_writenewsletter_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('cupon', django_quill.fields.QuillField(default='¡Usa el código de descuento SPECIAL50 al realizar tu compra para aplicar el 50% de descuento!')),
            ],
        ),
    ]
