# Generated by Django 4.0.4 on 2023-11-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_writeoferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoferta',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='writeoferta',
            name='title',
        ),
    ]
